### ISSUE TITLE
Incompatibility with edittable plugin

### ISSUE THREAD

**Issue by swiehr** [michitux/dokuwiki-plugin-saveandedit#3]
Using save and edit together with edittable plugin has quite interesting effects:
1. Start with a page having some text and a table
2. Go into edittable mode, check save and edit, do some changes and save
   -> check in another tab: table is now completely gone, other text still exists
3. Do some more edits and save (still checked)
   -> check in another tab: page is now empty (i.e. non-existent)
4. Uncheck save and edit, do some changes and save
   -> page now consists only of table

**Comment by michitux** [comment]
I could reproduce this. I have added several fixes for this in the new plugin version that I've just released. At least for me this works now under DokuWiki Greebo. This might also be fixed for releases before Greebo but I have not tested this.
