### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by gregoryloichot** [michitux/dokuwiki-plugin-saveandedit#34]
Hi, 

Just want to know if there is any plans to make a release with the recent merges ?

If not, would it be okay if we officially fork the plugin to benefit the entire community with the latest fixes?

All the best.

**Comment by michitux** [comment]
The download already points to the master branch so any user who installs the plugin already gets the latest version. However, I've just added the workflow by @glensc and performed a release which seems to have worked.
