### ISSUE TITLE
Undefined index error on PHP5.6

### ISSUE THREAD

**Issue by rozenlicht** [michitux/dokuwiki-plugin-saveandedit#4]
Using the saveandedit plugin under PHP5.6 with DokuWiki 2017-02-19e "Frusterick Manners" causes an undefined index error when saving.
`Undefined index: saveandedit on line 71 in action.php`

The line of code on 71:
`$attrs = $_REQUEST['saveandedit'] ? array('checked' => 'checked') : array();`

The following alteration should fix this issue:
`$attrs = !empty($_REQUEST['saveandedit']) ? array('checked' => 'checked') : array();`

**Comment by michitux** [comment]
Fixed in #5
