### ISSUE TITLE
Undefined function

### ISSUE THREAD

**Issue by gaetanlord** [michitux/dokuwiki-plugin-saveandedit#6]
Hi

Just upgraded to Greebo from Frusterick Manners.

If I do not select "continue editing after saving" all is good.

But if I do and try to save when selected , I get a 500 from the web server and the apache log report the following

[Tue Apr 24 16:11:38.328136 2018] [php7:error] [pid 4704] [client ::1:54626] PHP Fatal error:  Uncaught Error: Call to undefined function act_permcheck() in /home/gaetan/Dropbox/home/gaetan/Office/www/dokuwiki/lib/plugins/saveandedit/action.php:36\nStack trace:\n#0 /home/gaetan/Dropbox/home/gaetan/Office/www/dokuwiki/inc/events.php(229): action_plugin_saveandedit->handle_action_act_preprocess(Object(Doku_Event), NULL)\n#1 /home/gaetan/Dropbox/home/gaetan/Office/www/dokuwiki/inc/events.php(70): Doku_Event_Handler->process_event(Object(Doku_Event), 'BEFORE')\n#2 /home/gaetan/Dropbox/home/gaetan/Office/www/dokuwiki/inc/ActionRouter.php(80): Doku_Event->advise_before()\n#3 /home/gaetan/Dropbox/home/gaetan/Office/www/dokuwiki/inc/ActionRouter.php(48): dokuwiki\\ActionRouter->setupAction('save')\n#4 /home/gaetan/Dropbox/home/gaetan/Office/www/dokuwiki/inc/ActionRouter.php(60): dokuwiki\\ActionRouter->__construct()\n#5 /home/gaetan/Dropbox/home/gaetan/Office/www/dokuwiki/inc/actions.php(16): dokuwiki\\ActionRouter::getInstance(true)\n#6 /home/gaetan/Dropbox/home/gaetan/Office/www/dokuwiki/doku.php(120): act_dispatch()\n# in /home/gaetan/Dropbox/home/gaetan/Office/www/dokuwiki/lib/plugins/saveandedit/action.php on line 36, referer: http://localhost/dokuwiki/doku.php/projects/nextcloud?do=edit

The file lib/plugins/saveandedit/action.php have a call to act_permcheck, but this function is not available anymore. I guess it is a regresssion from the previous version. On the previous versions, that function was declared in inc/action.php.

**Comment by michitux** [comment]
Thank you very much for the bug report. The action handling in dokuwiki has been completely changed in the Greebo release, that's why that function doesn't exist anymore. I will have a look how the plugin can be adapted to work with the new release. I will try to get this fixed in the next days but I can't promise anything.

**Comment by michitux** [comment]
I have just released a new version of the plugin that works with DokuWiki release Greebo.
